### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by keren-cw** [cloudwalk/android-pos-pinpadservice#1]
The Readme does not cover:

- what external libs are required
- where to find them
- where to install them

This could be a nice improvement to this documentation.

**Comment by mauriciospinardi-cloudwalk** [comment]
For some strange reason I'm not being able to assign @alinerezendeCW and @AlvesCE with me to this issue... but you're invited, guys (as we previously discussed).

**Comment by keren-cw** [comment]
Hey! I just added them to this repository with the proper permission level ;
