### ISSUE TITLE
Verifone Pinpad Service v1.1.6 using BC v001.31

### ISSUE THREAD

**Issue by mauriciospinardi-cloudwalk** [cloudwalk/android-pos-pinpadservice#4]
Verifone has provided a new version of its core ABECS components: BC v001.31. It is supposed to fix the color of the status bar during a PIN capture operation (previously fixed blue).
We need to perform full certification tests to ensure there was no regressions in comparison with Verifone Pinpad Service v1.1.5, which uses BC v001.29.

**Comment by mauriciospinardi-cloudwalk** [comment]
@CW-romedeiros I have scheduled a meeting tomorrow for we to discuss how to tackle this task alongside a few others which may required the UL BTT and the certification environment.
Current expectation, if no issues are found, is for BETA release next week, alongside InfinitePay v1.2.6.

**Comment by mauriciospinardi-cloudwalk** [comment]
Here is the debug file, pre-built:
- [verifone-io.cloudwalk.pos.pinpadservice-1.1.6-220419-armeabi-v7a-debug.zip](https://github.com/cloudwalk/android-pos-pinpadservice/files/8515927/verifone-io.cloudwalk.pos.pinpadservice-1.1.6-220419-armeabi-v7a-debug.zip)

**Comment by CW-romedeiros** [comment]
Follows the L3 results:

Mastercard: no regression observed, all tests pass
Elo: no regression observed, all tests pass


We are waiting for the fix of the Visa environment to finish this validation.
